// <auto-generated />
namespace Lab004.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Scenario4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Scenario4));
        
        string IMigrationMetadata.Id
        {
            get { return "202003181505017_Scenario4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
