//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.DataAccess.Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPhotosModelContainer : DbContext
    {
        public MyPhotosModelContainer()
            : base("name=MyPhotosModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        // test
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}